FROM oven/bun:1.2.6 as base

WORKDIR /app
ARG NEXT_PUBLIC_CIVIC_AUTH_KEY
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG JWT_SECRET
ARG UPLOADTHING_TOKEN
ARG HELIUS_RPC_KEY
ARG KV_URL
ARG KV_REST_API_READ_ONLY_TOKEN
ARG REDIS_URL

ENV NEXT_PUBLIC_CIVIC_AUTH_KEY=${NEXT_PUBLIC_CIVIC_AUTH_KEY}
ENV UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
ENV UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV JWT_SECRET=${JWT_SECRET}
ENV UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
ENV HELIUS_RPC_KEY=${HELIUS_RPC_KEY}
ENV KV_URL=${KV_URL}
ENV KV_REST_API_READ_ONLY_TOKEN=${KV_REST_API_READ_ONLY_TOKEN}
ENV REDIS_URL=${REDIS_URL}

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile --ignore-scripts

COPY . .

RUN bun run build

FROM oven/bun:1.2.6-slim as runtime

WORKDIR /app

COPY --from=base /app/.next ./.next
COPY --from=base /app/public ./public
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/node_modules ./node_modules

EXPOSE 3000

# Start the Next.js application
CMD ["bun", "run", "start"]