[phases.setup]
nixPkgs = [
  "bun", "nodejs_20",
  "python3", "gnumake", "gcc", "pkg-config",
  "libusb1", "systemd" 
]

[phases.install]
cmds = ["bun run install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmds = "bun run dev"
